---

'on':
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: py.test
  lint:
    name: Run linter for dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hadolint linting
        uses: brpaz/hadolint-action@master
